# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'progressos.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
import time


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(530, 449)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("files/LSTime.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 531, 451))
        self.frame.setStyleSheet("background-color:#9C27B0;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 531, 83))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#fff;\n""background:#2F0C35;\n""padding:5px 0;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(260, 100, 1, 220))
        self.line.setStyleSheet("background:rgba(255,255,255,.3)")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(0, 83, 530, 1))
        self.line_2.setStyleSheet("background:rgba(255,255,255,.3)")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(0, 330, 530, 1))
        self.line_3.setStyleSheet("background:rgba(255,255,255,.3)")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.btnApagar = QtWidgets.QPushButton(self.frame)
        self.btnApagar.setGeometry(QtCore.QRect(175, 360, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.btnApagar.setFont(font)
        self.btnApagar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnApagar.setStyleSheet(
            "QPushButton {background:#2F0C35;border:none;border-radius:5px;border:2px solid transparent;border-left:2px solid #fff;border-bottom:2px solid #fff;color:#fff;}QPushButton:hover{border:none;background:#0A1C84;border-right:2px solid #fff;border-top:2px solid #fff;color:#fff;}")
        self.btnApagar.setObjectName("btnApagar")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background:rgba(255,255,255,.8);\n""color:#9C27B0;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(270, 100, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:#fff;\n""background:transparent;")
        self.label_3.setObjectName("label_3")
        self.lblData = QtWidgets.QLabel(self.frame)
        self.lblData.setGeometry(QtCore.QRect(350, 100, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.lblData.setFont(font)
        self.lblData.setStyleSheet("color:#fff;\n""background:transparent;")
        self.lblData.setObjectName("lblData")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(270, 150, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background:transparent;\n""color:#9C27B0")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.lblTempo = QtWidgets.QLabel(self.frame)
        self.lblTempo.setGeometry(QtCore.QRect(275, 210, 121, 111))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(55)
        font.setBold(True)
        font.setWeight(75)
        self.lblTempo.setFont(font)
        self.lblTempo.setStyleSheet("background:transparent;\n""color:#0F4F93;")
        self.lblTempo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTempo.setObjectName("lblTempo")
        self.lblMinutos = QtWidgets.QLabel(self.frame)
        self.lblMinutos.setGeometry(QtCore.QRect(396, 210, 121, 111))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.lblMinutos.setFont(font)
        self.lblMinutos.setStyleSheet("background:transparent;\n""color:#0F4F93;")
        self.lblMinutos.setObjectName("lblMinutos")
        self.cbData = QtWidgets.QComboBox(self.frame)
        self.cbData.setGeometry(QtCore.QRect(20, 150, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.cbData.setFont(font)
        self.cbData.setStyleSheet("color:#9926AC;\n""background:rgba(255,255,255,.7);")
        self.cbData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.cbData.setIconSize(QtCore.QSize(20, 20))
        self.cbData.setDuplicatesEnabled(False)
        self.cbData.setFrame(True)
        self.cbData.setObjectName("cbData")
        self.lblImagem = QtWidgets.QLabel(self.frame)
        self.lblImagem.setGeometry(QtCore.QRect(0, 84, 531, 245))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.lblImagem.setFont(font)
        self.lblImagem.setStyleSheet("background:transparent;border-radius:10px;color:#9C27B0;")
        self.lblImagem.setText("")
        self.lblImagem.setPixmap(QtGui.QPixmap("files/img-background.jpg"))
        self.lblImagem.setScaledContents(True)
        self.lblImagem.setAlignment(QtCore.Qt.AlignCenter)
        self.lblImagem.setObjectName("lblImagem")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(267, 150, 251, 61))
        self.label_9.setStyleSheet("background:#fff;")
        self.label_9.setText("")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(267, 207, 251, 111))
        self.label_10.setStyleSheet("background:rgba(221,221,221,.8);border-radius:5px;")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(0, 84, 531, 366))
        self.label_4.setStyleSheet("background:rgba(0,0,0,.6);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(20, 190, 231, 128))
        self.label_7.setStyleSheet("background:rgba(3,3,3,.5);")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("files/img-background.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(0, 329, 531, 121))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("files/img-footer.jpg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_8.raise_()
        self.lblImagem.raise_()
        self.label.raise_()
        self.line_2.raise_()
        self.label_7.raise_()
        self.label_4.raise_()
        self.cbData.raise_()
        self.label_10.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_9.raise_()
        self.label_5.raise_()
        self.lblData.raise_()
        self.lblMinutos.raise_()
        self.lblTempo.raise_()
        self.line.raise_()
        self.btnApagar.raise_()
        self.line_3.raise_()

        self.database = 'progressos.db'
        self.lista = []
        self.ficheiro = 0

        self.cbData.currentIndexChanged.connect(self.selecionar_dados)
        self.btnApagar.clicked.connect(self.apagar_dados)

        self.retranslateUi(Dialog)
        self.cbData.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.selecionar_dados()
        self.visualizar_dados()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Progressos"))
        self.label.setText(_translate("Dialog", "PROGRESSOS DIÁRIOS"))
        self.btnApagar.setText(_translate("Dialog", "Apagar"))
        self.label_2.setText(_translate("Dialog", "Escolha Data"))
        self.label_3.setText(_translate("Dialog", "Data:"))
        self.lblData.setText(_translate("Dialog", ""))
        self.label_5.setText(_translate("Dialog", "Tempo Estudado"))
        self.lblTempo.setText(_translate("Dialog", ""))
        self.lblMinutos.setText(_translate("Dialog", ""))

    def mensagem(self):
        info = QtWidgets.QMessageBox()
        info.setIcon(QtWidgets.QMessageBox.Information)
        icone = QtGui.QIcon()
        icone.addPixmap(QtGui.QPixmap('files/LSTime.ico'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        info.setWindowIcon(icone)
        info.setWindowTitle('Excluído')
        info.setText('\nProgresso Excluído com Sucesso...\n')
        info.exec_()

    def visualizar_dados(self):
        conexao = sqlite3.connect(self.database)
        cursor = conexao.cursor()
        cursor.execute('select id, minutos, dataCadastro from progressos order by id desc')
        linhas = cursor.fetchall()
        for item in linhas:
            self.lista.append(item)
            file = str(item[0]) + ' - ' + str(item[2])
            self.ficheiro = int(item[0])
            self.cbData.addItem(file)
        if self.lista == []:
            self.ficheiro = 0
        conexao.close()

    def selecionar_dados(self):
        data = self.cbData.currentText()
        for item in self.lista:
            tipo = str(item[0]) + ' - ' + str(item[2])
            if tipo == data:
                self.ficheiro = int(item[0])
                self.lblData.setText(str(item[2]))
                self.lblTempo.setText(str(item[1]))
                self.lblMinutos.setText('Minutos')

    def apagar_dados(self):
        if self.ficheiro == 0 or self.ficheiro == '0':
            print('Nenhum Progresso foi gravado ainda!')
        else:
            questao = QtWidgets.QMessageBox.question(None, 'Excluir',
                                                     '\nTem certeza que deseja exluir este progresso?\n',
                                                     QtWidgets.QMessageBox.Ok | QtWidgets.QMessageBox.No)
            if questao == QtWidgets.QMessageBox.Ok:
                conexao = sqlite3.connect(self.database)
                cursor = conexao.cursor()
                try:
                    cursor.execute('DELETE FROM progressos WHERE id={}'.format(self.ficheiro))
                    conexao.commit()
                    conexao.close()
                    self.mensagem()
                    self.lista = []
                    self.cbData.clear()
                    self.lblData.setText('')
                    self.lblTempo.setText('')
                    self.lblMinutos.setText('')
                    self.visualizar_dados()
                except Exception as e:
                    print(e)
            else:
                pass


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
